---
title: "Predictions in ungaged basins workplan FY2018"
author: "Scott Worland, William Asquith, and Rodney Knight"
date: "10/7/2017"
output: html_document
---

### Overview

The primary goal of the RESTORE project is to produce quantative and qualitative measurements of watershed alteration for XXXX watersheds in the RESTORE footprint. Accomplishing this goal is dependent on a suite of basin characterisics for each watershed. These basin characteristics include streamflow statistics calculated from a hydrograph. However, XX% of the watersheds in the RESTORE footprint do not have a streamgage and the streamflow statistics need to be estimated for these basins. There are two primary ways to estimate streamflow statistics in ungaged basins: (1) predict a full hydrograph for a basin and calculate the statistics using the estimated hydrograph, or (2) directly predict the streamflow statistics. We are using the second approach.

### Basic idea behind direct prediction

In the simplest terms, direct prediction involves predicting streamflow statistics using basin characteristics derived primarily from gridded products. Examples of streamflow statistics that can be estimated are mean-annual flow, low streamflow values (i.e., 7Q10, minimum October flow, etc), high streamflow values (i.e., 100 year flood discharge), or any number of other values along a flow duration curve. These predictions are made using some form of multivariate regression. This could range from simple linear regression models such as ordinary least squares or censored regression to non-linear machine learning methods such as random forest models or neural networks. 

### Data needed for direct prediction

All of the data needed for direct prediction can be in the form of one large matrix where the required columns are:

* Unique ID for watershed
* Coordinates (centroid of watershed)
* Response variables: streamflow statistics to calculate (for the basins without a gage the values for this column will be NA)
* Explanatory variables: basin characteristics for every basin (including for basins without the streamflow statistics--we will need them for the final predictions)

### Workplan for direct prediction

Scott Worland and William Asquith will start with the same dataset and independently build prediction models using gaged basins for each response variable. Predictions in ungaged basins will be simulated using leave-one-out cross validation (LOO-CV). The LOO-CV predictions for each model and response variable will be stored in a matrix and various perfomance metrics will be calculated for each model. For example, the 7Q10 LOO-CV prediction matrix will have the following form:

```{r, echo=F}
library(kableExtra)

d <- data.frame(staid=c(001,002,003,004,"..."),
                observed=c(10.6,14.3,6.1,2.9,"..."),
                model1=c(8.1,11.5,6.4,1.5,"..."),
                model2=c(10.1,13.4,3.2,4.8,"..."))

knitr::kable(d,caption="Hypothetical LOO-CV prediction matrix for 7Q10") %>%
  kable_styling(bootstrap_options = c("striped", "hover"),full_width = F)
```





